import "./globals.css";
import { Bebas_Neue } from "next/font/google";

const Bebas = Bebas_Neue({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bebas",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased ${Bebas.variable}`}>{children}</body>
    </html>
  );
}
